name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: make setup
      - run: make lint

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.5.7
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
        with:
          coverageCommand: make test
          debug: true
          push: true
          cache-from: hexletcomponents/fastify-nodejs-application:latest
          cache-to: type=inline
          tags: hexletcomponents/fastify-nodejs-application:latest
